// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/m-mizutani/mdex/pkg/domain"
	"sync"
)

// Ensure, that FileScannerMock does implement domain.FileScanner.
// If this is not the case, regenerate this file with moq.
var _ domain.FileScanner = &FileScannerMock{}

// FileScannerMock is a mock implementation of domain.FileScanner.
//
//	func TestSomethingThatUsesFileScanner(t *testing.T) {
//
//		// make and configure a mocked domain.FileScanner
//		mockedFileScanner := &FileScannerMock{
//			ScanMarkdownFilesFunc: func(baseDir string) ([]domain.MarkdownFile, error) {
//				panic("mock out the ScanMarkdownFiles method")
//			},
//		}
//
//		// use mockedFileScanner in code that requires domain.FileScanner
//		// and then make assertions.
//
//	}
type FileScannerMock struct {
	// ScanMarkdownFilesFunc mocks the ScanMarkdownFiles method.
	ScanMarkdownFilesFunc func(baseDir string) ([]domain.MarkdownFile, error)

	// calls tracks calls to the methods.
	calls struct {
		// ScanMarkdownFiles holds details about calls to the ScanMarkdownFiles method.
		ScanMarkdownFiles []struct {
			// BaseDir is the baseDir argument value.
			BaseDir string
		}
	}
	lockScanMarkdownFiles sync.RWMutex
}

// ScanMarkdownFiles calls ScanMarkdownFilesFunc.
func (mock *FileScannerMock) ScanMarkdownFiles(baseDir string) ([]domain.MarkdownFile, error) {
	if mock.ScanMarkdownFilesFunc == nil {
		panic("FileScannerMock.ScanMarkdownFilesFunc: method is nil but FileScanner.ScanMarkdownFiles was just called")
	}
	callInfo := struct {
		BaseDir string
	}{
		BaseDir: baseDir,
	}
	mock.lockScanMarkdownFiles.Lock()
	mock.calls.ScanMarkdownFiles = append(mock.calls.ScanMarkdownFiles, callInfo)
	mock.lockScanMarkdownFiles.Unlock()
	return mock.ScanMarkdownFilesFunc(baseDir)
}

// ScanMarkdownFilesCalls gets all the calls that were made to ScanMarkdownFiles.
// Check the length with:
//
//	len(mockedFileScanner.ScanMarkdownFilesCalls())
func (mock *FileScannerMock) ScanMarkdownFilesCalls() []struct {
	BaseDir string
} {
	var calls []struct {
		BaseDir string
	}
	mock.lockScanMarkdownFiles.RLock()
	calls = mock.calls.ScanMarkdownFiles
	mock.lockScanMarkdownFiles.RUnlock()
	return calls
}
