// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/m-mizutani/mdex/pkg/domain"
	"io"
	"sync"
)

// Ensure, that NotionClientMock does implement domain.NotionClient.
// If this is not the case, regenerate this file with moq.
var _ domain.NotionClient = &NotionClientMock{}

// NotionClientMock is a mock implementation of domain.NotionClient.
//
//	func TestSomethingThatUsesNotionClient(t *testing.T) {
//
//		// make and configure a mocked domain.NotionClient
//		mockedNotionClient := &NotionClientMock{
//			AppendBlocksFunc: func(ctx context.Context, pageID string, blocks []interface{}) error {
//				panic("mock out the AppendBlocks method")
//			},
//			ArchivePageFunc: func(ctx context.Context, pageID string) error {
//				panic("mock out the ArchivePage method")
//			},
//			CreatePageFunc: func(ctx context.Context, databaseID string, properties map[string]interface{}, blocks []interface{}) (string, error) {
//				panic("mock out the CreatePage method")
//			},
//			EnsureDatabasePropertiesFunc: func(ctx context.Context, databaseID string, properties []domain.PropertySpec) error {
//				panic("mock out the EnsureDatabaseProperties method")
//			},
//			GetTitlePropertyFunc: func(ctx context.Context, databaseID string) (string, error) {
//				panic("mock out the GetTitleProperty method")
//			},
//			QueryDatabaseFunc: func(ctx context.Context, databaseID string, pathProperty string, hashProperty string, domainProperty string, domainValue string) ([]domain.NotionPage, error) {
//				panic("mock out the QueryDatabase method")
//			},
//			UploadFileFunc: func(ctx context.Context, filename string, contentType string, body io.Reader) (string, error) {
//				panic("mock out the UploadFile method")
//			},
//		}
//
//		// use mockedNotionClient in code that requires domain.NotionClient
//		// and then make assertions.
//
//	}
type NotionClientMock struct {
	// AppendBlocksFunc mocks the AppendBlocks method.
	AppendBlocksFunc func(ctx context.Context, pageID string, blocks []interface{}) error

	// ArchivePageFunc mocks the ArchivePage method.
	ArchivePageFunc func(ctx context.Context, pageID string) error

	// CreatePageFunc mocks the CreatePage method.
	CreatePageFunc func(ctx context.Context, databaseID string, properties map[string]interface{}, blocks []interface{}) (string, error)

	// EnsureDatabasePropertiesFunc mocks the EnsureDatabaseProperties method.
	EnsureDatabasePropertiesFunc func(ctx context.Context, databaseID string, properties []domain.PropertySpec) error

	// GetTitlePropertyFunc mocks the GetTitleProperty method.
	GetTitlePropertyFunc func(ctx context.Context, databaseID string) (string, error)

	// QueryDatabaseFunc mocks the QueryDatabase method.
	QueryDatabaseFunc func(ctx context.Context, databaseID string, pathProperty string, hashProperty string, domainProperty string, domainValue string) ([]domain.NotionPage, error)

	// UploadFileFunc mocks the UploadFile method.
	UploadFileFunc func(ctx context.Context, filename string, contentType string, body io.Reader) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// AppendBlocks holds details about calls to the AppendBlocks method.
		AppendBlocks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PageID is the pageID argument value.
			PageID string
			// Blocks is the blocks argument value.
			Blocks []interface{}
		}
		// ArchivePage holds details about calls to the ArchivePage method.
		ArchivePage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PageID is the pageID argument value.
			PageID string
		}
		// CreatePage holds details about calls to the CreatePage method.
		CreatePage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DatabaseID is the databaseID argument value.
			DatabaseID string
			// Properties is the properties argument value.
			Properties map[string]interface{}
			// Blocks is the blocks argument value.
			Blocks []interface{}
		}
		// EnsureDatabaseProperties holds details about calls to the EnsureDatabaseProperties method.
		EnsureDatabaseProperties []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DatabaseID is the databaseID argument value.
			DatabaseID string
			// Properties is the properties argument value.
			Properties []domain.PropertySpec
		}
		// GetTitleProperty holds details about calls to the GetTitleProperty method.
		GetTitleProperty []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DatabaseID is the databaseID argument value.
			DatabaseID string
		}
		// QueryDatabase holds details about calls to the QueryDatabase method.
		QueryDatabase []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DatabaseID is the databaseID argument value.
			DatabaseID string
			// PathProperty is the pathProperty argument value.
			PathProperty string
			// HashProperty is the hashProperty argument value.
			HashProperty string
			// DomainProperty is the domainProperty argument value.
			DomainProperty string
			// DomainValue is the domainValue argument value.
			DomainValue string
		}
		// UploadFile holds details about calls to the UploadFile method.
		UploadFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filename is the filename argument value.
			Filename string
			// ContentType is the contentType argument value.
			ContentType string
			// Body is the body argument value.
			Body io.Reader
		}
	}
	lockAppendBlocks             sync.RWMutex
	lockArchivePage              sync.RWMutex
	lockCreatePage               sync.RWMutex
	lockEnsureDatabaseProperties sync.RWMutex
	lockGetTitleProperty         sync.RWMutex
	lockQueryDatabase            sync.RWMutex
	lockUploadFile               sync.RWMutex
}

// AppendBlocks calls AppendBlocksFunc.
func (mock *NotionClientMock) AppendBlocks(ctx context.Context, pageID string, blocks []interface{}) error {
	if mock.AppendBlocksFunc == nil {
		panic("NotionClientMock.AppendBlocksFunc: method is nil but NotionClient.AppendBlocks was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		PageID string
		Blocks []interface{}
	}{
		Ctx:    ctx,
		PageID: pageID,
		Blocks: blocks,
	}
	mock.lockAppendBlocks.Lock()
	mock.calls.AppendBlocks = append(mock.calls.AppendBlocks, callInfo)
	mock.lockAppendBlocks.Unlock()
	return mock.AppendBlocksFunc(ctx, pageID, blocks)
}

// AppendBlocksCalls gets all the calls that were made to AppendBlocks.
// Check the length with:
//
//	len(mockedNotionClient.AppendBlocksCalls())
func (mock *NotionClientMock) AppendBlocksCalls() []struct {
	Ctx    context.Context
	PageID string
	Blocks []interface{}
} {
	var calls []struct {
		Ctx    context.Context
		PageID string
		Blocks []interface{}
	}
	mock.lockAppendBlocks.RLock()
	calls = mock.calls.AppendBlocks
	mock.lockAppendBlocks.RUnlock()
	return calls
}

// ArchivePage calls ArchivePageFunc.
func (mock *NotionClientMock) ArchivePage(ctx context.Context, pageID string) error {
	if mock.ArchivePageFunc == nil {
		panic("NotionClientMock.ArchivePageFunc: method is nil but NotionClient.ArchivePage was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		PageID string
	}{
		Ctx:    ctx,
		PageID: pageID,
	}
	mock.lockArchivePage.Lock()
	mock.calls.ArchivePage = append(mock.calls.ArchivePage, callInfo)
	mock.lockArchivePage.Unlock()
	return mock.ArchivePageFunc(ctx, pageID)
}

// ArchivePageCalls gets all the calls that were made to ArchivePage.
// Check the length with:
//
//	len(mockedNotionClient.ArchivePageCalls())
func (mock *NotionClientMock) ArchivePageCalls() []struct {
	Ctx    context.Context
	PageID string
} {
	var calls []struct {
		Ctx    context.Context
		PageID string
	}
	mock.lockArchivePage.RLock()
	calls = mock.calls.ArchivePage
	mock.lockArchivePage.RUnlock()
	return calls
}

// CreatePage calls CreatePageFunc.
func (mock *NotionClientMock) CreatePage(ctx context.Context, databaseID string, properties map[string]interface{}, blocks []interface{}) (string, error) {
	if mock.CreatePageFunc == nil {
		panic("NotionClientMock.CreatePageFunc: method is nil but NotionClient.CreatePage was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DatabaseID string
		Properties map[string]interface{}
		Blocks     []interface{}
	}{
		Ctx:        ctx,
		DatabaseID: databaseID,
		Properties: properties,
		Blocks:     blocks,
	}
	mock.lockCreatePage.Lock()
	mock.calls.CreatePage = append(mock.calls.CreatePage, callInfo)
	mock.lockCreatePage.Unlock()
	return mock.CreatePageFunc(ctx, databaseID, properties, blocks)
}

// CreatePageCalls gets all the calls that were made to CreatePage.
// Check the length with:
//
//	len(mockedNotionClient.CreatePageCalls())
func (mock *NotionClientMock) CreatePageCalls() []struct {
	Ctx        context.Context
	DatabaseID string
	Properties map[string]interface{}
	Blocks     []interface{}
} {
	var calls []struct {
		Ctx        context.Context
		DatabaseID string
		Properties map[string]interface{}
		Blocks     []interface{}
	}
	mock.lockCreatePage.RLock()
	calls = mock.calls.CreatePage
	mock.lockCreatePage.RUnlock()
	return calls
}

// EnsureDatabaseProperties calls EnsureDatabasePropertiesFunc.
func (mock *NotionClientMock) EnsureDatabaseProperties(ctx context.Context, databaseID string, properties []domain.PropertySpec) error {
	if mock.EnsureDatabasePropertiesFunc == nil {
		panic("NotionClientMock.EnsureDatabasePropertiesFunc: method is nil but NotionClient.EnsureDatabaseProperties was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DatabaseID string
		Properties []domain.PropertySpec
	}{
		Ctx:        ctx,
		DatabaseID: databaseID,
		Properties: properties,
	}
	mock.lockEnsureDatabaseProperties.Lock()
	mock.calls.EnsureDatabaseProperties = append(mock.calls.EnsureDatabaseProperties, callInfo)
	mock.lockEnsureDatabaseProperties.Unlock()
	return mock.EnsureDatabasePropertiesFunc(ctx, databaseID, properties)
}

// EnsureDatabasePropertiesCalls gets all the calls that were made to EnsureDatabaseProperties.
// Check the length with:
//
//	len(mockedNotionClient.EnsureDatabasePropertiesCalls())
func (mock *NotionClientMock) EnsureDatabasePropertiesCalls() []struct {
	Ctx        context.Context
	DatabaseID string
	Properties []domain.PropertySpec
} {
	var calls []struct {
		Ctx        context.Context
		DatabaseID string
		Properties []domain.PropertySpec
	}
	mock.lockEnsureDatabaseProperties.RLock()
	calls = mock.calls.EnsureDatabaseProperties
	mock.lockEnsureDatabaseProperties.RUnlock()
	return calls
}

// GetTitleProperty calls GetTitlePropertyFunc.
func (mock *NotionClientMock) GetTitleProperty(ctx context.Context, databaseID string) (string, error) {
	if mock.GetTitlePropertyFunc == nil {
		panic("NotionClientMock.GetTitlePropertyFunc: method is nil but NotionClient.GetTitleProperty was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DatabaseID string
	}{
		Ctx:        ctx,
		DatabaseID: databaseID,
	}
	mock.lockGetTitleProperty.Lock()
	mock.calls.GetTitleProperty = append(mock.calls.GetTitleProperty, callInfo)
	mock.lockGetTitleProperty.Unlock()
	return mock.GetTitlePropertyFunc(ctx, databaseID)
}

// GetTitlePropertyCalls gets all the calls that were made to GetTitleProperty.
// Check the length with:
//
//	len(mockedNotionClient.GetTitlePropertyCalls())
func (mock *NotionClientMock) GetTitlePropertyCalls() []struct {
	Ctx        context.Context
	DatabaseID string
} {
	var calls []struct {
		Ctx        context.Context
		DatabaseID string
	}
	mock.lockGetTitleProperty.RLock()
	calls = mock.calls.GetTitleProperty
	mock.lockGetTitleProperty.RUnlock()
	return calls
}

// QueryDatabase calls QueryDatabaseFunc.
func (mock *NotionClientMock) QueryDatabase(ctx context.Context, databaseID string, pathProperty string, hashProperty string, domainProperty string, domainValue string) ([]domain.NotionPage, error) {
	if mock.QueryDatabaseFunc == nil {
		panic("NotionClientMock.QueryDatabaseFunc: method is nil but NotionClient.QueryDatabase was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		DatabaseID     string
		PathProperty   string
		HashProperty   string
		DomainProperty string
		DomainValue    string
	}{
		Ctx:            ctx,
		DatabaseID:     databaseID,
		PathProperty:   pathProperty,
		HashProperty:   hashProperty,
		DomainProperty: domainProperty,
		DomainValue:    domainValue,
	}
	mock.lockQueryDatabase.Lock()
	mock.calls.QueryDatabase = append(mock.calls.QueryDatabase, callInfo)
	mock.lockQueryDatabase.Unlock()
	return mock.QueryDatabaseFunc(ctx, databaseID, pathProperty, hashProperty, domainProperty, domainValue)
}

// QueryDatabaseCalls gets all the calls that were made to QueryDatabase.
// Check the length with:
//
//	len(mockedNotionClient.QueryDatabaseCalls())
func (mock *NotionClientMock) QueryDatabaseCalls() []struct {
	Ctx            context.Context
	DatabaseID     string
	PathProperty   string
	HashProperty   string
	DomainProperty string
	DomainValue    string
} {
	var calls []struct {
		Ctx            context.Context
		DatabaseID     string
		PathProperty   string
		HashProperty   string
		DomainProperty string
		DomainValue    string
	}
	mock.lockQueryDatabase.RLock()
	calls = mock.calls.QueryDatabase
	mock.lockQueryDatabase.RUnlock()
	return calls
}

// UploadFile calls UploadFileFunc.
func (mock *NotionClientMock) UploadFile(ctx context.Context, filename string, contentType string, body io.Reader) (string, error) {
	if mock.UploadFileFunc == nil {
		panic("NotionClientMock.UploadFileFunc: method is nil but NotionClient.UploadFile was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Filename    string
		ContentType string
		Body        io.Reader
	}{
		Ctx:         ctx,
		Filename:    filename,
		ContentType: contentType,
		Body:        body,
	}
	mock.lockUploadFile.Lock()
	mock.calls.UploadFile = append(mock.calls.UploadFile, callInfo)
	mock.lockUploadFile.Unlock()
	return mock.UploadFileFunc(ctx, filename, contentType, body)
}

// UploadFileCalls gets all the calls that were made to UploadFile.
// Check the length with:
//
//	len(mockedNotionClient.UploadFileCalls())
func (mock *NotionClientMock) UploadFileCalls() []struct {
	Ctx         context.Context
	Filename    string
	ContentType string
	Body        io.Reader
} {
	var calls []struct {
		Ctx         context.Context
		Filename    string
		ContentType string
		Body        io.Reader
	}
	mock.lockUploadFile.RLock()
	calls = mock.calls.UploadFile
	mock.lockUploadFile.RUnlock()
	return calls
}
